:- consult(wn_ant).
:- consult(wn_at).
:- consult(wn_cls).
:- consult(wn_cs).
:- consult(wn_der).
:- consult(wn_ent).
:- consult(wn_fr).
:- consult(wn_g).
:- consult(wn_hyp).
:- consult(wn_ins).
:- consult(wn_mm).
:- consult(wn_mp).
:- consult(wn_ms).
:- consult(wn_per).
:- consult(wn_ppl).
:- consult(wn_s).
:- consult(wn_sa).
:- consult(wn_sim).
:- consult(wn_sk).
:- consult(wn_syntax).
:- consult(wn_vgp).